fix: misc inconsistencies and prompts

diff --git a/deploy b/deploy
--- a/deploy
+++ b/deploy
@@ -5,7 +5,7 @@
 ################################################################################
 
 command_exists () {
-  hash "$1" 2> /dev/null
+  hash "$1" 2>/dev/null
 }
 brew_install () {
   if [[ -n $2 ]]; then
@@ -65,6 +65,7 @@ echo
 
 PS1_RESET="\033[0m"
 PS1_YELLOW="\033[93m"
+PS1_RED="\e[91m"
 
 if [[ -s "$HOME/.deploy" ]]; then
   source "$HOME/.deploy"
@@ -86,7 +87,7 @@ if [[ ! -n $GITEMAIL ]]; then
 fi
 
 if [[ ! -n $MASEMAIL ]]; then
-  printf "Enter your ${PS1_YELLOW}email address${PS1_RESET} to be recorded in any newly created git commits:\n"
+  printf "Enter your ${PS1_YELLOW}Apple ID${PS1_RESET} to install apps from the App Store:\n"
   read MASEMAIL
 fi
 
@@ -106,21 +107,24 @@ EOF
 CURRENTPATH="`pwd`";
 
 # Prevent awkward prompt in middle of deploy; Request acces to root in advance.
-echo "Please enter your password to proceed with deploy:"
-if [[ ! $(sudo echo 0) ]]; then exit; fi
+if [[ $(sudo -n echo 0 &>/dev/null; echo $?) -ne 0 ]]; then
+  printf "Please enter your ${PS1_YELLOW}password${PS1_RESET} to proceed with deploy:\n"
+  if [[ ! $(sudo echo 0) ]]; then exit; fi
+fi
 
 # Install Xcode Command Line Tools.
-if [[ ! -f /usr/bin/xcrun ]]; then
+if [[ $(xcode-select -p &>/dev/null; echo $?) -ne 0 ]]; then
   echo "Installing Xcode Command Line Tools..."
   sudo -S xcode-select --install
 fi
 
 # Enable command line tools
-sudo -S xcode-select --switch /Library/Developer/CommandLineTools
+sudo -S xcode-select -r
 
 # Make sure Xcode Command Line Tools are installed.
 if ! command_exists ruby; then
-  echo >&2 "Please install Xcode Command Line Tools manually. Aborting."
+  echo
+  printf >&2 "${PS1_RED}Please install Xcode Command Line Tools manually. Aborting.${PS1_RESET}\n"
   exit 1
 fi
 
@@ -134,7 +138,8 @@ fi
 
 # Abort if brew installation did not complete.
 if ! command_exists brew; then
-  echo >&2 "Please install brew manually. Aborting."
+  echo
+  printf >&2 "${PS1_RED}Please install brew manually. Aborting.${PS1_RESET}\n"
   exit 1
 fi
 
@@ -150,7 +155,13 @@ fi
 if [ ! `brew list | grep mas` ]; then
   brew install mas
 fi
-# mas signin "$MASEMAIL"
+if [[ "$(mas account | grep "Warning: Not signed in")" ]]; then
+  # mas signin "$MASEMAIL"
+  echo
+  printf >&2 "${PS1_RED}Please sign into the Mac App Store app manually. Then restart the deploy script.${PS1_RESET}\n"
+  exit 1
+fi
+
 
 ################################################################################
 # Development tools.                                                           #
@@ -158,10 +169,12 @@ fi
 
 # Set git defaults.
 if [[ $(git config --global user.name) != "$GITNAME" ]]; then
+  echo
   echo "Setting git defaults."
   git config --global user.name "$GITNAME"
   git config --global user.email "$GITEMAIL"
   git config --global push.default 'upstream'
+  echo
 fi
 
 # XQuartz, used for X11 apps.
@@ -290,6 +303,7 @@ fi
 # Additional Tasks #
 ####################
 
+echo
 echo "################################################################################"
 echo
 echo "Deployment complete."
@@ -297,6 +311,9 @@ echo
 echo "################################################################################"
 echo
 echo "Just a few more things to take care of:"
+echo
+echo "- Update any open shell environments to get access to all commands."
+echo "  # source ~/.bash_profile"
 echo
 echo "- Manually install macid at https://macid.co/"
 echo
